#!/usr/bin/env groovy

// Continuous Integration script to build mkdocs in Docker
// Author: mauricio.diaz@inria.fr

pipeline {
  agent none
    stages {
      stage('Build the docs') {
        agent {
          dockerfile {
              filename 'Dockerfile'
              reuseNode true
          }
        }
        environment {
          CONDA_HOME = '/opt/conda'
          PATH = "/opt/conda/bin:/opt/conda/condabin:$PATH"
        }
        steps {
          echo 'My branch name is ${BRANCH_NAME}'
          sh 'echo "My branch name is ${BRANCH_NAME}"'
          sh 'echo "Agent name: ${NODE_NAME}"'
          sh 'pwd'
          sh '$MAMBA_EXE info'
          sh 'printenv'
          //sh '. /usr/local/bin/_activate_current_env.sh'
          sh '''#!/bin/bash
            eval "$(/bin/micromamba shell hook --shell=bash)"
            //$MAMBA_EXE activate base
            poetry about
            make build.book
          '''
          stash(name: 'doc_html', includes: 'jupyter-book/_build/**')
        }
      }
      stage('Deploy') {
        parallel {
          stage('Deploy site') {
            agent { label 'ubuntu' }
            when {
                branch 'main'
            }
            steps {
              echo 'Deploying in webserver...'
              unstash(name: 'doc_html')
              sshPublisher(
                publishers: [
                  sshPublisherDesc(
                    configName: 'web',
                    transfers: [
                      sshTransfer(
                        cleanRemote: false,
                        excludes: '',
                        execCommand: '',
                        execTimeout: 120000,
                        flatten: false,
                        makeEmptyDirs: false,
                        noDefaultExcludes: false,
                        patternSeparator: '[, ]+',
                        remoteDirectory: 'clinicadl_tuto_2023',
                        remoteDirectorySDF: false,
                        removePrefix: '',
                        sourceFiles: 'jupyter-book/_build/**')
                        ],
                      usePromotionTimestamp: false,
                      useWorkspaceInPromotion: false,
                      verbose: false)
                ]
              )
              echo 'Finish uploading artifacts'
            }
          }
        }
      }
    }
//    post {
//      failure {
//        mail to: 'clinicadl-ci@inria.fr',
//          subject: "This build of the welcome guide has failed: ${currentBuild.fullDisplayName}",
//          body: "Something is wrong with the build of the welcome guide ${env.BUILD_URL}"
//      }
//    }
}

